@Mentor_HostAddress = http://localhost:5070

### Создать комнату (администратор)
POST {{Mentor_HostAddress}}/api/admin/rooms
Content-Type: application/json

{
  "name": "Комната 101",
  "roomClass": "Комфорт",
  "pricePerNight": 4500,
  "description": "Двухместная комната с видом на город"
}

### Получить все комнаты
GET {{Mentor_HostAddress}}/api/rooms
Accept: application/json

### Забронировать комнату
# Подставьте roomId из ответа создания комнаты
POST {{Mentor_HostAddress}}/api/bookings
Content-Type: application/json

{
  "roomId": "00000000-0000-0000-0000-000000000000",
  "userId": "user-1",
  "checkIn": "2026-08-01",
  "checkOut": "2026-08-05"
}

### Получить бронирования пользователя
GET {{Mentor_HostAddress}}/api/bookings?userId=user-1
Accept: application/json
